#if !canImport(ObjectiveC)
import XCTest

extension LambdaApiNIOTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LambdaApiNIOTests = [
        ("testGetNextInvocation", testGetNextInvocation),
        ("testInit", testInit),
        ("testPostInitializationError", testPostInitializationError),
        ("testPostInvocationError", testPostInvocationError),
        ("testPostInvocationResponse", testPostInvocationResponse),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LambdaApiNIOTests.__allTests__LambdaApiNIOTests),
    ]
}
#endif
