#if !canImport(ObjectiveC)
import XCTest

extension LambdaApiNIOTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LambdaApiNIOTests = [
        ("testGetNextInvocation", testGetNextInvocation),
        ("testInit", testInit),
        ("testPostInitializationError", testPostInitializationError),
        ("testPostInvocationError", testPostInvocationError),
        ("testPostInvocationResponse", testPostInvocationResponse),
    ]
}

extension NIOLambdaHandlerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NIOLambdaHandlerTests = [
        ("testAsyncNIOLambdaHandler", testAsyncNIOLambdaHandler),
        ("testCodableAsyncNIOLambdaHandler", testCodableAsyncNIOLambdaHandler),
        ("testCodableSyncNIOLambdaHandler", testCodableSyncNIOLambdaHandler),
        ("testDictionaryAsyncNIOLambdaHandler", testDictionaryAsyncNIOLambdaHandler),
        ("testDictionarySyncNIOLambdaHandler", testDictionarySyncNIOLambdaHandler),
        ("testSyncNIOLambdaHandler", testSyncNIOLambdaHandler),
    ]
}

extension SprinterNIOTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SprinterNIOTests = [
        ("testRegisterAsyncNIOTyped", testRegisterAsyncNIOTyped),
        ("testRegisterAsyncNIOWithCompletion", testRegisterAsyncNIOWithCompletion),
        ("testRegisterSyncNIOTyped", testRegisterSyncNIOTyped),
        ("testRegisterSyncNIOWithCompletion", testRegisterSyncNIOWithCompletion),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LambdaApiNIOTests.__allTests__LambdaApiNIOTests),
        testCase(NIOLambdaHandlerTests.__allTests__NIOLambdaHandlerTests),
        testCase(SprinterNIOTests.__allTests__SprinterNIOTests),
    ]
}
#endif
